'use client'

import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, ChevronDown, Instagram, Menu, MessageCircle, Package, Pencil, Plus, Settings2, Star, Users, X } from 'lucide-react'

const localImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Video%202026-09-04%20at%201.35.44%20PM-nOMWRFqVHCED5Zn0vGPbLn90QCwtCw.mp4'
const logoImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-04%20151746-VRQ9DxNa9M93suFkaZEo0mQUQFA0K2.png'
const cuts = [
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-04%20145510-62PhkY3eGc8w3lDoCgtjNs3vqThEsN.png',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-04%20145559-F3ufndvRDTh557VnLEStvxW3mc7VD0.png',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-09-04%20145539-jDG9RbLoDcr92hOciGYKVhmCBkQEzq.png',
]

// Placeholder content only: the definitive values remain editable data, not hard-coded UI.
const barbers = [
  { name: 'Tu próximo barbero', specialty: 'Fades · Barba · Detalles', phone: '+54 9 11 0000 0000', image: cuts[0] },
  { name: 'Especialista JF', specialty: 'Corte clásico · Estilo moderno', phone: '+54 9 11 0000 0000', image: cuts[1] },
]
const products = [
  { name: 'Máquina profesional', type: 'Equipamiento', price: '$120.000' },
  { name: 'Pomada mate JF', type: 'Styling', price: '$18.500' },
  { name: 'Trimmer de precisión', type: 'Equipamiento', price: '$74.000' },
]
const navItems = [['Servicios', 'servicios'], ['Equipo', 'equipo'], ['Galería', 'galeria'], ['Botica', 'botica'], ['Reseñas', 'resenas'], ['Ubicación', 'ubicacion']]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [adminOpen, setAdminOpen] = useState(false)
  const [activeFaq, setActiveFaq] = useState<number | null>(null)

  useEffect(() => {
    document.body.style.overflow = menuOpen || adminOpen ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [menuOpen, adminOpen])

  return (
    <main className="jf-site min-h-screen overflow-x-hidden bg-[#080808] text-[#f1eee6] selection:bg-[#c9a24b] selection:text-[#080808]">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[0.08] bg-[#080808]/92 backdrop-blur-md">
        <div className="mx-auto flex h-[88px] max-w-[1440px] items-center gap-6 px-5 sm:px-8 lg:px-10">
          <a href="#inicio" className="group flex min-w-0 items-center gap-3.5" onClick={() => setMenuOpen(false)}>
            <img src={logoImage} alt="JF Barbershop" className="size-12 shrink-0 border border-[#c9a24b]/50 object-cover" />
            <span className="min-w-0"><span className="block truncate text-[20px] font-black uppercase leading-none tracking-[-0.03em]">JF BARBERSHOP</span><span className="mt-2 block text-[10px] font-semibold uppercase tracking-[0.32em] text-[#c9a24b]">BUENOS AIRES VE</span></span>
          </a>
          <div className="ml-auto flex items-center gap-2 sm:gap-3">
            <div className="hidden items-center gap-2 rounded-full border border-white/[0.12] bg-white/[0.025] px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[0.13em] text-white/70 lg:flex"><span className="size-2 rounded-full bg-[#c9a24b] shadow-[0_0_10px_rgba(201,162,75,.55)]" />Abierto hoy: 09:00 — 21:00</div>
            <a href="#ubicacion" className="hidden rounded-full bg-[#c9a24b] px-5 py-3 text-[10px] font-black uppercase tracking-[0.12em] text-[#080808] shadow-[0_8px_30px_rgba(201,162,75,.14)] transition duration-300 hover:-translate-y-0.5 hover:bg-[#dfbb68] sm:block">Vení sin turno</a>
            <button aria-label="Abrir menú" onClick={() => setMenuOpen(true)} className="group flex size-11 items-center justify-center border border-white/[0.13] bg-white/[0.02] transition hover:border-[#c9a24b]/70 hover:bg-[#c9a24b] hover:text-[#080808]"><Menu className="size-5 transition group-hover:scale-90" /></button>
          </div>
        </div>
      </header>

      <aside className={`fixed inset-0 z-[70] ${menuOpen ? 'pointer-events-auto' : 'pointer-events-none'}`} aria-hidden={!menuOpen}>
        <button aria-label="Cerrar menú" onClick={() => setMenuOpen(false)} className={`absolute inset-0 bg-black/70 backdrop-blur-[2px] transition-opacity duration-500 ${menuOpen ? 'opacity-100' : 'opacity-0'}`} />
        <div className={`absolute right-0 top-0 h-full w-full max-w-[520px] border-l border-white/[0.1] bg-[#0c0c0c] px-6 py-6 shadow-[-30px_0_90px_rgba(0,0,0,.55)] transition-transform duration-500 ease-[cubic-bezier(.22,1,.36,1)] sm:px-10 ${menuOpen ? 'translate-x-0' : 'translate-x-full'}`}>
          <div className="flex items-center justify-between border-b border-white/[0.1] pb-5"><div><span className="font-mono text-[10px] uppercase tracking-[0.3em] text-[#c9a24b]">JF / MENU</span><p className="mt-1 text-xs uppercase tracking-[0.15em] text-white/35">Barbería · Buenos Aires VE</p></div><button aria-label="Cerrar menú" onClick={() => setMenuOpen(false)} className="flex size-11 items-center justify-center border border-white/10 transition hover:border-[#c9a24b] hover:text-[#c9a24b]"><X /></button></div>
          <nav className="mt-10">{navItems.map(([label, id], index) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)} className="group flex items-center justify-between border-b border-white/[0.08] py-5 transition hover:px-2"><span className="flex items-center gap-5"><span className="font-mono text-[10px] text-[#c9a24b]">0{index + 1}</span><span className="text-3xl font-black uppercase tracking-[-0.04em] sm:text-4xl">{label}</span></span><ArrowUpRight className="size-5 text-white/25 transition duration-300 group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#c9a24b]" /></a>)}</nav>
          <div className="absolute bottom-7 left-6 right-6 border-t border-white/[0.1] pt-5 sm:left-10 sm:right-10"><a href="#ubicacion" onClick={() => setMenuOpen(false)} className="flex w-full items-center justify-center gap-2 bg-[#c9a24b] px-5 py-4 text-[10px] font-black uppercase tracking-[0.16em] text-[#080808] transition hover:bg-[#dfbb68]"><ArrowDownRight className="size-4" /> Vení sin turno</a></div>
        </div>
      </aside>

      <section id="inicio" className="relative flex min-h-[760px] items-end overflow-hidden border-b border-white/[0.08] px-5 pb-12 pt-32 sm:min-h-[850px] sm:px-8 lg:min-h-screen lg:px-10 lg:pb-20">
        <video className="absolute inset-0 size-full object-cover opacity-35 grayscale" autoPlay muted loop playsInline poster={cuts[1]}><source src={localImage} type="video/mp4" /></video>
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_40%,rgba(201,162,75,.09),transparent_30%),linear-gradient(90deg,#080808_0%,rgba(8,8,8,.78)_48%,rgba(8,8,8,.38)_100%)]" /><div className="absolute inset-0 bg-gradient-to-t from-[#080808] via-transparent to-[#080808]/30" />
        <div className="relative z-10 mx-auto w-full max-w-[1440px]">
          <div className="mb-8 inline-flex items-center gap-3 rounded-full border border-[#c9a24b]/40 bg-[#080808]/55 px-4 py-2.5 text-[10px] font-bold uppercase tracking-[0.24em] text-[#d8b35b] animate-[fadeUp_.8s_ease-out_both]"><span>//</span> Barbería venezolana VE · Desde 2021 en CABA</div>
          <h1 className="max-w-[980px] text-[clamp(4rem,10vw,9.6rem)] font-black uppercase leading-[.82] tracking-[-.065em] animate-[fadeUp_.9s_.08s_ease-out_both]">Tu estilo puede<br /><span className="bg-gradient-to-r from-[#f3d28a] via-[#c9a24b] to-[#936d22] bg-clip-text text-transparent">hacer más ruido.</span></h1>
          <div className="mt-10 grid gap-8 border-t border-white/[0.14] pt-5 md:grid-cols-[1fr_auto] md:items-end animate-[fadeUp_.9s_.16s_ease-out_both]"><div><p className="max-w-2xl text-xl font-medium leading-8 text-white/90 sm:text-2xl">JF Barbershop <span className="text-[#c9a24b]">|</span> Barbería Buenos Aires. Sin reservas, con carácter.</p><p className="mt-3 max-w-xl text-sm leading-6 text-white/45">No alcanza con un corte estándar. Hoy destaca quien cultiva un ritual impecable.</p></div><a href="#servicios" className="group inline-flex items-center gap-3 text-[10px] font-black uppercase tracking-[0.18em] text-white">Explorá JF <span className="flex size-12 items-center justify-center rounded-full bg-[#c9a24b] text-[#080808] transition duration-500 group-hover:rotate-45 group-hover:bg-[#dfbb68]"><ArrowDownRight /></span></a></div>
        </div>
      </section>

      <section id="servicios" className="border-b border-white/[0.08] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><SectionLabel number="01" text="Servicios" /><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="max-w-xl text-5xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-7xl">Un buen corte<br /><span className="text-white/25">se nota.</span></h2><p className="mt-7 max-w-md text-sm leading-7 text-white/45">Los servicios que aparecen acá se alimentarán de la configuración real de JF. Sin inventar precios ni servicios.</p></div><div className="divide-y divide-white/[0.1] border-y border-white/[0.1]">{['Cortes', 'Barba', 'Corte + barba', 'Detalles'].map((item, i) => <div key={item} className="group flex items-center justify-between py-6 transition hover:px-3"><div className="flex items-center gap-5"><span className="font-mono text-[10px] text-[#c9a24b]">0{i + 1}</span><span className="text-2xl font-bold uppercase tracking-[-.03em] sm:text-3xl">{item}</span></div><ArrowUpRight className="size-5 text-white/20 transition group-hover:text-[#c9a24b]" /></div>)}</div></div></div></section>

      <section id="equipo" className="border-b border-white/[0.08] bg-[#0d0d0d] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><SectionLabel number="02" text="El equipo" /><div className="mb-14 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="max-w-4xl text-5xl font-black uppercase leading-[.86] tracking-[-.06em] sm:text-7xl lg:text-8xl">Elegí al barbero.<br /><span className="text-[#c9a24b]">Volvé por el corte.</span></h2><p className="max-w-sm text-sm leading-6 text-white/40">Cada perfil tendrá sus datos reales y su WhatsApp individual cuando estén cargados desde Admin.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{barbers.map((barber, index) => <article key={barber.name} className="group border border-white/[0.1] bg-[#111] transition duration-500 hover:-translate-y-1 hover:border-[#c9a24b]/45"><div className="relative overflow-hidden"><img src={barber.image} alt="Perfil de barbero" className="aspect-[4/5] w-full object-cover grayscale transition duration-700 group-hover:scale-[1.04] group-hover:grayscale-0" /><span className="absolute left-4 top-4 border border-[#c9a24b]/50 bg-[#080808]/75 px-3 py-2 font-mono text-[9px] uppercase tracking-[0.16em] text-[#d8b35b]">Perfil pendiente</span></div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="text-2xl font-black uppercase tracking-[-.04em]">{barber.name}</h3><p className="mt-2 text-xs uppercase tracking-[.13em] text-white/40">{barber.specialty}</p></div><span className="font-mono text-[10px] text-white/25">0{index + 1}</span></div><a href={`https://wa.me/${barber.phone.replace(/\D/g, '')}`} target="_blank" rel="noreferrer" className="mt-6 flex items-center justify-center gap-2 border border-[#c9a24b]/50 bg-[#c9a24b] px-4 py-3 text-[10px] font-black uppercase tracking-[.14em] text-[#080808] transition hover:bg-[#dfbb68]"><MessageCircle className="size-4" /> WhatsApp directo</a></div></article>)}</div></div></section>

      <section className="border-b border-white/[0.08] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><SectionLabel number="03" text="Mientras esperás" /><h2 className="mt-8 text-5xl font-black uppercase leading-[.86] tracking-[-.06em] sm:text-7xl">Tu turno.<br /><span className="text-white/25">Tu momento.</span></h2></div><div className="grid border-y border-white/[0.1] sm:grid-cols-3 sm:divide-x sm:divide-white/[0.1]"><Amenity index="01" title="PlayStation" text="Una partida mientras llega tu turno." /><Amenity index="02" title="Pool" text="Jugá, relajate y hacé tiempo." /><Amenity index="03" title="Dardos" text="Competí con quien te acompaña." /></div></div></div></section>

      <section id="galeria" className="border-b border-white/[0.08] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><SectionLabel number="04" text="Galería" /><div className="mb-12 flex items-end justify-between gap-6"><h2 className="text-5xl font-black uppercase leading-[.86] tracking-[-.06em] sm:text-7xl">Hecho<br /><span className="text-[#c9a24b]">en JF.</span></h2><span className="hidden font-mono text-[10px] uppercase tracking-[.2em] text-white/30 sm:block">Trabajos reales / JF</span></div><div className="grid grid-cols-12 gap-3">{cuts.map((cut, i) => <div key={cut} className={`group relative overflow-hidden border border-white/[0.08] ${i === 0 ? 'col-span-12 md:col-span-6' : 'col-span-6 md:col-span-3'}`}><img src={cut} alt={`Trabajo realizado en JF ${i + 1}`} className={`w-full object-cover grayscale transition duration-700 group-hover:scale-[1.04] group-hover:grayscale-0 ${i === 0 ? 'aspect-[4/3]' : 'aspect-[3/4]'}`} /><div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/75 to-transparent px-4 pb-4 pt-12"><span className="font-mono text-[9px] uppercase tracking-[.18em] text-[#d8b35b]">JF / 0{i + 1}</span><ArrowUpRight className="size-4 text-white/70" /></div></div>)}</div></div></section>

      <section id="botica" className="border-b border-white/[0.08] bg-[#c9a24b] px-5 py-24 text-[#080808] sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><SectionLabel number="05" text="Botica" dark /><div className="mt-8 grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="text-5xl font-black uppercase leading-[.86] tracking-[-.06em] sm:text-7xl">Lo que usamos.<br /><span className="opacity-40">Lo que recomendamos.</span></h2><p className="mt-7 max-w-md text-sm leading-6 text-black/55">Los productos y precios reales serán los que Joel cargue desde el panel de administración.</p></div><div className="grid gap-px bg-black/20 md:grid-cols-3">{products.map(product => <article key={product.name} className="bg-[#c9a24b] p-6 transition hover:bg-[#dfbb68]"><Package className="mb-16 size-6" /><p className="text-[9px] font-bold uppercase tracking-[.2em] opacity-55">{product.type}</p><h3 className="mt-3 text-xl font-black uppercase tracking-[-.03em]">{product.name}</h3><div className="mt-8 flex items-center justify-between border-t border-black/20 pt-4 text-sm"><span>{product.price}</span><ArrowUpRight className="size-5" /></div></article>)}</div></div></div></section>

      <section id="resenas" className="border-b border-white/[0.08] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><SectionLabel number="06" text="Reseñas" /><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><h2 className="text-5xl font-black uppercase leading-[.86] tracking-[-.06em] sm:text-7xl">Que hable<br /><span className="text-[#c9a24b]">la gente.</span></h2><div className="mt-8 flex items-center gap-3 text-[#c9a24b]"><Star className="fill-current" /><Star className="fill-current" /><Star className="fill-current" /><Star className="fill-current" /><Star className="fill-current" /></div></div><div className="divide-y divide-white/[0.1] border-y border-white/[0.1]">{[0,1,2].map(i => <div key={i} className="py-7"><p className="text-lg leading-8 text-white/65">Las reseñas reales de Google aparecerán acá cuando estén conectadas al contenido definitivo de JF.</p><span className="mt-4 block font-mono text-[9px] uppercase tracking-[.18em] text-[#c9a24b]">Reseña pendiente / 0{i + 1}</span></div>)}</div></div></div></section>

      <section id="ubicacion" className="px-5 py-24 sm:px-8 lg:px-10 lg:py-36"><div className="mx-auto max-w-[1440px]"><SectionLabel number="07" text="Ubicación" /><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="text-5xl font-black uppercase leading-[.86] tracking-[-.06em] sm:text-8xl">Vení.<br /><span className="text-[#c9a24b]">Sin turno.</span></h2><div className="mt-10 space-y-6 border-t border-white/[0.12] pt-6 text-sm leading-7 text-white/55"><p className="text-white">Presidente Luis Sáenz Peña 338<br />CABA, Buenos Aires</p><p>Lun a Sáb · 09:00 a 21:00<br />Barbería venezolana · Desde 2021</p><a href="https://instagram.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-white transition hover:text-[#c9a24b]"><Instagram className="size-4" /> Instagram <ArrowUpRight className="size-3" /></a></div></div><div className="min-h-[360px] overflow-hidden border border-white/[0.1] bg-[#0d0d0d]"><iframe title="Ubicación de JF Barbershop" src="https://www.google.com/maps?q=Presidente%20Luis%20Saenz%20Pe%C3%B1a%20338%2C%20CABA%2C%20Buenos%20Aires&output=embed" className="size-full min-h-[360px] grayscale opacity-80" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></div></section>

      <section className="border-y border-white/[0.08] bg-[#0d0d0d] px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><SectionLabel number="08" text="Preguntas" /><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><h2 className="text-5xl font-black uppercase leading-[.86] tracking-[-.06em] sm:text-7xl">Antes de<br /><span className="text-white/25">venir.</span></h2><div className="border-y border-white/[0.1]">{['¿Necesito reservar?', '¿Cómo funciona la atención?', '¿Puedo elegir barbero?', '¿Dónde queda JF?'].map((question, i) => <div key={question} className="border-b border-white/[0.1] last:border-b-0"><button onClick={() => setActiveFaq(activeFaq === i ? null : i)} className="flex w-full items-center justify-between py-6 text-left"><span className="flex items-center gap-5"><span className="font-mono text-[10px] text-[#c9a24b]">0{i + 1}</span><span className="text-lg font-bold uppercase tracking-[-.02em] sm:text-xl">{question}</span></span><ChevronDown className={`size-5 text-[#c9a24b] transition-transform duration-300 ${activeFaq === i ? 'rotate-180' : ''}`} /></button><div className={`grid transition-[grid-template-rows,opacity] duration-300 ${activeFaq === i ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'}`}><p className="min-h-0 overflow-hidden pb-0 text-sm leading-7 text-white/45">{i === 0 ? 'JF trabaja con atención por orden de llegada. No se gestionan reservas online.' : i === 1 ? 'Llegás al local y esperás tu turno. La idea es mantener el flujo de atención sin huecos.' : i === 2 ? 'Los perfiles y sus WhatsApp individuales aparecerán en la web cuando estén cargados con la información real.' : 'JF Barbershop está en Presidente Luis Sáenz Peña 338, CABA.'}</p></div></div>)}</div></div></div></section>

      <footer className="px-5 py-10 sm:px-8 lg:px-10"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-8 border-t border-white/[0.1] pt-7 sm:flex-row sm:items-end"><div><div className="text-3xl font-black uppercase tracking-[-.04em]">JF BARBERSHOP<span className="text-[#c9a24b]">.</span></div><div className="mt-2 text-[9px] font-semibold uppercase tracking-[.28em] text-[#c9a24b]">BUENOS AIRES VE</div></div><div className="text-left sm:text-right"><p className="text-xs uppercase tracking-[.15em] text-white/30">El corte importa.</p><p className="mt-1 text-xs uppercase tracking-[.15em] text-white/50">Cómo te hacen sentir, también.</p></div></div><div className="mt-8 flex flex-col justify-between gap-3 border-t border-white/[0.06] pt-4 text-[9px] uppercase tracking-[.18em] text-white/25 sm:flex-row"><span>JF Barbershop © 2026</span><button onClick={() => setAdminOpen(true)} className="flex items-center gap-2 self-start transition hover:text-[#c9a24b]"><Settings2 className="size-3" /> Administración</button></div></div></footer>

      {adminOpen && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-5 backdrop-blur-md"><div className="w-full max-w-2xl border border-black/10 bg-[#f1eee6] p-6 text-[#11110f] shadow-2xl sm:p-10"><div className="flex items-start justify-between"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-black/50">Panel de administración</p><h2 className="mt-2 text-4xl font-black uppercase tracking-tight">Contenido JF</h2></div><button onClick={() => setAdminOpen(false)} aria-label="Cerrar administración" className="transition hover:text-[#9b762d]"><X /></button></div><div className="mt-10 grid gap-3 sm:grid-cols-2"><AdminCard icon={<Users />} title="Barberos" text="Nombres, fotos, especialidades y WhatsApp" /><AdminCard icon={<Package />} title="Productos" text="Productos y precios" /><AdminCard icon={<Pencil />} title="Trabajos" text="Galería y fotos de cortes" /><AdminCard icon={<Star />} title="Reseñas" text="Opiniones visibles en la web" /></div><button className="mt-8 flex w-full items-center justify-center gap-2 bg-[#11110f] px-5 py-4 text-xs font-bold uppercase tracking-[.18em] text-[#c9a24b]"><Plus className="size-4" /> Agregar contenido</button><p className="mt-5 text-center text-xs text-black/45">La interfaz pública usa esta misma estructura visual; la fuente definitiva de contenido seguirá siendo la base editable.</p></div></div>}
    </main>
  )
}

function SectionLabel({ number, text, dark = false }: { number: string; text: string; dark?: boolean }) { return <div className={`flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.28em] ${dark ? 'text-black/70' : 'text-[#c9a24b]'}`}><span>//</span><span>{number}</span><span>{text}</span></div> }
function Amenity({ index, title, text }: { index: string; title: string; text: string }) { return <article className="p-6 sm:p-7"><span className="font-mono text-[10px] text-[#c9a24b]">{index}</span><h3 className="mt-16 text-2xl font-black uppercase tracking-[-.03em]">{title}</h3><p className="mt-3 text-sm leading-6 text-white/40">{text}</p></article> }
function AdminCard({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <button className="flex items-start gap-4 border border-black/10 p-5 text-left transition hover:border-black/40"><span>{icon}</span><span><strong className="block text-lg font-bold uppercase">{title}</strong><small className="mt-1 block leading-5 text-black/50">{text}</small></span></button> }
